### ISSUE TITLE
NoNodeAvailableException and ReceiveTimeoutTransportException  in  es-java-client-sample project 

### ISSUE THREAD

**Issue by prashantgupta27** [satendrakumar/es-java-client-sample#2]
when we will run the project then both problems are arising NoNodeAvailableException and ReceiveTimeoutTransportException(already we have added data in elastic search and check  ) and my port no is 9200
Please help me......

Sep 28, 2018 12:45:38 PM org.elasticsearch.plugins.PluginsService <init>
INFO: [Matsu'o Tsurayaba] modules [], plugins [delete-by-query], sites []
Sep 28, 2018 12:45:44 PM org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
INFO: [Matsu'o Tsurayaba] failed to get node info for {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9200}, disconnecting...
ReceiveTimeoutTransportException[[][localhost/127.0.0.1:9200][cluster:monitor/nodes/liveness] request_id [0] timed out after [5001ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

getMatchAllQueryCount query =>{
  "match_all" : { }
}
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at com.es.service.CountService.getMatchAllQueryCount(CountService.java:19)
	at com.es.app.ESApp.main(ESApp.java:19)

**Comment by satendrakumar** [comment]
@prashantgupta27 what is the version of elasticsearch?

**Comment by prashantgupta27** [comment]
This is version details
{
  "status" : 200,
  "name" : "Jack-in-the-Box",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by satendrakumar** [comment]
@prashantgupta27 "1.7.2" correct? This sample is built for "2.3.2" version. It will not work for  **"1.7.2"** 
Any reason using old version ?

**Comment by prashantgupta27** [comment]
no, any reason

**Comment by prashantgupta27** [comment]
which version are install?

**Comment by satendrakumar** [comment]
This sample is built for elasticsearch "2.3.2" version. I will recommend either use 2.4.x or 6.4.x.

**Comment by prashantgupta27** [comment]
ok i am checking.

**Comment by satendrakumar** [comment]
@prashantgupta27 we moved code  [here](https://github.com/techmonad/learning-elasticsearch-java) and also update for Elasticsearch 2.4.1.

**Comment by prashantgupta27** [comment]
I am using eclipse  again  error

Oct 05, 2018 12:53:01 PM org.elasticsearch.plugins.PluginsService <init>
INFO: [Stacy X] modules [], plugins [delete-by-query], sites []
Oct 05, 2018 12:53:07 PM org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
INFO: [Stacy X] failed to get node info for {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9200}, disconnecting...
ReceiveTimeoutTransportException[[][localhost/127.0.0.1:9200][cluster:monitor/nodes/liveness] request_id [0] timed out after [5001ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

getMatchAllQueryCount query =>{
  "match_all" : { }
}
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at com.es.service.CountService.getMatchAllQueryCount(CountService.java:19)
	at com.es.app.ESApp.main(ESApp.java:24)

**Comment by prashantgupta27** [comment]
{
  "name" : "UpdG6Fm",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Lnl6QxyNRR-crsOORrjlwA",
  "version" : {
    "number" : "6.4.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "04711c2",
    "build_date" : "2018-09-26T13:34:09.098244Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by prashantgupta27** [comment]
we have checked your new project but still, it throws the same erroar.
add value in elasticsearch db  successfully 

Oct 05, 2018 1:25:16 PM org.elasticsearch.plugins.PluginsService <init>
INFO: [Makkari] modules [], plugins [delete-by-query], sites []
Oct 05, 2018 1:25:21 PM org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
INFO: [Makkari] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9200}, disconnecting...
ReceiveTimeoutTransportException[[][127.0.0.1:9200][cluster:monitor/nodes/liveness] request_id [0] timed out after [5000ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:696)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

getMatchAllQueryCount query =>{
  "match_all" : { }
}
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at com.techmonad.es.service.CountService.getMatchAllQueryCount(CountService.java:19)
	at com.techmonad.es.app.ESApp.main(ESApp.java:26)

**Comment by prashantgupta27** [comment]
Hello Sir, Thanks for the help now it's working fine.
can you share the project references API ?

**Comment by satendrakumar** [comment]
You can find detailed doc https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.4/index.html
